In [2]:
import stl
import numpy as np
from mpl_toolkits import mplot3d
from matplotlib import pyplot
from sklearn.cluster import KMeans
import collections
import math

In [8]:
upper = stl.mesh.Mesh.from_file('upper.stl')
center = stl.mesh.Mesh.from_file('center.stl')
lower = stl.mesh.Mesh.from_file('lower.stl')
porsche = stl.mesh.Mesh.from_file('porsche.stl')
mesh_list = [upper, lower, center, porsche]

In [9]:
def mesh_info(mesh):
    volume, cog, inertia = mesh.get_mass_properties()
    print("Volume                                  = {0}".format(volume))
    print("Position of the center of gravity (COG) = {0}".format(cog))
    print("Inertia matrix at expressed at the COG  = {0}".format(inertia[0,:]))
    print("                                          {0}".format(inertia[1,:]))
    print("                                          {0}".format(inertia[2,:]))


In [10]:
for mesh in mesh_list:
    mesh_info(mesh)

Volume                                  = 17505.212826922758
Position of the center of gravity (COG) = [-4.11188649  1.14166148 -1.64187906]
Inertia matrix at expressed at the COG  = [ 3722607.92730567   720796.81880517  -151951.00275387]
                                          [  720796.81880517  5115989.32436042    78490.08406334]
                                          [ -151951.00275387    78490.08406334  9337689.74422334]
Volume                                  = 17505.212826922758
Position of the center of gravity (COG) = [-4.11188649  1.14166148 -1.64187906]
Inertia matrix at expressed at the COG  = [ 3722607.92730567   720796.81880517  -151951.00275387]
                                          [  720796.81880517  5115989.32436042    78490.08406334]
                                          [ -151951.00275387    78490.08406334  9337689.74422334]
Volume                                  = 43136.822344634464
Position of the center of gravity (COG) = [ 2.95544145 -3.23646552 -1

In [7]:
mesh_list[0].rotate([0.0, 0.5, 0.0], math.radians(10))

mesh_list[0].save("rot_porsche.stl")